const type = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_FAIL: "SIGNUP_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_START: "LOGIN_START",
  LOGIN_FAIL: "LOGIN_FAIL",
};

export default type;
